FROM rocker/tidyverse:3.6.2
RUN R -e 'install.packages("remotes")'
RUN R -e 'remotes::install_github("r-lib/remotes", ref = "97bbf81")'
RUN R -e 'remotes::install_cran("shiny")'
RUN R -e 'remotes::install_cran("data.table")'
RUN R -e 'remotes::install_cran("PtxGenerator")'
RUN R -e 'remotes::install_cran("golem")'
RUN R -e 'remotes::install_cran("processx")'
RUN R -e 'remotes::install_cran("attempt")'
RUN R -e 'remotes::install_cran("DT")'
RUN R -e 'remotes::install_cran("glue")'
RUN R -e 'remotes::install_cran("htmltools")'
RUN R -e 'remotes::install_cran("pkgload")'
RUN R -e 'remotes::install_cran("shinydashboard")'
RUN R -e 'remotes::install_cran("readxl")'
RUN R -e 'remotes::install_cran("officer")'
RUN R -e 'remotes::install_cran("flextable")'
RUN R -e 'remotes::install_cran("lubridate")'
RUN R -e 'remotes::install_cran("bizdays")'
RUN R -e 'remotes::install_cran("ggplot2")'
RUN R -e 'remotes::install_cran("ggrepel")'
RUN R -e 'remotes::install_cran("timevis")'
RUN R -e 'remotes::install_cran("shinycssloaders")'
RUN R -e 'remotes::install_cran("tidyr")'
COPY PtxExample_*.tar.gz /app.tar.gz
RUN R -e 'remotes::install_local("/app.tar.gz")'
CMD R -e "options('shiny.port'=$PORT,shiny.host='0.0.0.0');PtxExample::run_app()"
